# -*- coding: utf-8 -*-
"""Privbayes-datasynthesizer-25JAN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cp-Tb3rFe5J4dJuL2W_2LSyWWOtREzU_

This was presented to seniors for the Privbayes Implmenetation!
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /

# Commented out IPython magic to ensure Python compatibility.
# %rm -rf /Privbayes-Implementation/
!git clone https://github.com/0hex7/Privbayes-Implementation.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /Privbayes-Implementation/

!python3 setup.py install
!pip install -r requirements.txt
!pip install DataSynthesizer

# Commented out IPython magic to ensure Python compatibility.
# %cd /Privbayes-Implementation/privbayes-datasynthesizer/code/

# Commented out IPython magic to ensure Python compatibility.
# %run privbayes.py --dataset /adult_tiny.csv --rows 10000 --compare 3

